#!/usr/bin/perl
#
# gd2.pl -- create GD::Graph "linespoints" graph
#
use strict;
use warnings;
use Carp;
use GD::Graph::linespoints;
my %dataset = ( 1 => 3,
               2 => 17,
       3 => 34,
       4 => 23,
       5 => 25,
       6 => 20,
       7 => 12,

       8 => 3,
       9 => 1
);
# create new image
my $graph = new GD::Graph::linespoints(600, 300);
   
# discover maximum values of x and y for graph parameters
my( $xmax) = sort {$b <=> $a} keys %dataset;
my( $ymax) = sort {$b <=> $a} values %dataset;
# how many ticks to put on y axis
my $yticks = int($ymax / 5) + 1;
   
# define input arrays and enter 0 if undefined x value
my(@xsizes) = (0 .. $xmax);
my(@ycounts) = ();
foreach my $x (@xsizes) {
   if ( defined $dataset{$x}) {
       push @ycounts, $dataset{$x};
   }else{
       push @ycounts, 0;
   }
}
# define input data
# need to do separately so show_values will work
my $data = GD::Graph::Data->new(
   [ 
xsizes,
     
ycounts
  ]
);
# use show_values to show values of data next to points
# use $values to suppress printing of value for x=3
my $values = $data->copy;
$values->set_y(1, 3, undef);
# set parameters for graph
$graph->set(
   transparent                => 0,
   title                => "Summary of mutation data",
   x_label                => 'Mutants per cluster',
   y_label                => 'Number of mutants',
   x_all_ticks                => 1,
   y_all_ticks                => 0,
   y_tick_number        => $yticks,
   zero_axis                => 0,
   zero_axis_only        => 0,
   show_values         => $values,
);
   
# plot the data on the graph
my $gd = $graph->plot(
   [ 
xsizes,
     
ycounts
   ]
);
# output file
my $pngfile = "gdgraph2.png";
unless(open(PNG, ">$pngfile")) {

   croak "Cannot open $pngfile:$!\n";
}
binmode PNG;
print PNG $gd->png;
A variety of image viewing programs may be used to display your results while you're doing
Linux system and elsewhere. I often use xv, and while it usually works quite well, it seems to
new data. It's common for a system's user interface to allow you to click on the image file's
loaded.
many possibilities, all of which are easily incorporated into your Perl programs for output to
files or sent to a web browser from your CGI program.

8.5 Resources
(Graphics Press).
Although I don't demonstrate their use in this book, I want to mention two more full-featured
graphics software packages that are free, and very useful if you'll be doing graphics to any
extent:

for creating images. Over 60 different file formats are supported, compared to the
supported, enabling you to create animation, thumbnails, and apply many image
processing functions, for example.

The Gimp (GNU Image Manipulation Program) is very much like the Photoshop
modules, starting with the Gimp.pm module, that provide Perl programmers with
access to its functionality.
image creation and manipulation software, at no cost.

8.6 Exercises
Exercise 8.1
Add an argument "linelength=>50" to Restrictionmap to set the length of lines in
the graphic output.
Exercise 8.2
What happens if you request a graphic type for which no corresponding method has
behavior of the module?
Exercise 8.3
to rework the annotation lines when more than one type of enzyme appears on an
Exercise 8.4
Add header information such as filename, count of restriction sites for each enzyme,
and date, to the text or PNG or JPEG graphic generated by _drawmap_text or
_drawmap_png or _drawmap_jpg.
Exercise 8.5
you right-justify the numbers in the allotted space?
Exercise 8.6
easier to find a particular base position.
Exercise 8.7
In _drawmap_png or _drawmap_jpg, instead of putting the enzyme names in
of enzyme in the map a different color and type of box and add a key that shows
which enzyme matches up with each color/box.
more? Do you need to change the output of _drawmap_text to accomplish this?
Exercise 8.8
the image-generating CGI script rebase_png. Then use the CGI for an HTML tag such
as:
print img({ -src => "/cgi-bin/rebase_png?enzyme=EcoRI;fileseq=
    sampleecori.dna2" });
In this way, you can embed a dynamically generated image into a larger HTML
shown by itself in the web browser.
Exercise 8.9
The _drawmap_jpg and _drawmap_png methods are almost identical. Add a third

type desired for output. Then rewrite _drawmap_jpg and _drawmap_png so that they're
much shorter. Now add a _drawmap_wbmp method.
Exercise 8.10
The _drawmap_png method assumes that annotation lines contain spaces while
compute and leads to a simplification of program logic. What if there is an annotation
line that has no spaces because it annotates a line of sequence that is solid,
wall-to-wall restriction sites? Invent another method of distinguishing between
annotation and sequence lines.
Exercise 8.11
Use GD::Graph to make a different representation of a restriction map.

Bioperl is a collection of more than 500 Perl modules for bioinformatics that have been
unrestrictive copyright), and its home is http://bioperl.org.
chapter, you'll be well prepared to delve deeper into the riches of Bioperl, and, if you've also
to read the Bioperl code and contribute to the project yourself.
know object-oriented programming can still use the Bioperl modules with just a bit of extra
information, as outlined in Chapter 3.
can dip into for help when writing your own programs. Its goal is to provide good working
solutions to common bioinformatics tasks and to speed your program development.
One of the best things about Bioperl is that it's an open source project, meaning that
is available to anyone interested. If you've learned enough about Perl for bioinformatics to
involved in Bioperl if you have the time and inclination.

9.1 The Growth of Bioperl
The practice of freely distributing Perl software for bioinformatics over the Internet began
around 1992. Gradually, Perl became more and more popular for biology applications.
[1] The
release of Perl Version 5 and its support for object-oriented programming accelerated the
development of reusable modules for biology at many research centers around the world.
well as the talent and funding, for these efforts. The Bioperl project, officially organized in
primary source of Bioperl code and documentation.
[1] See, for example, the article "How Perl Saved the Human Genome Project" by Lincoln Stein at
http://bioperl.org/GetStarted/tpj_ls_bio.html.
enough documented, that it is a must for Perl programming in bioinformatics. The

9.2 Installing Bioperl
and Perl modules on which Bioperl depends. You will probably want to use Perl's CPAN to
fetch and install Bioperl.
operating systems. It's part of the Bioperl distribution and is located at 
add a few additional comments that may help with installation.
Here's how to get Bioperl on different platforms:

On Unix/Linux, if you download the tar file from the web site, you merely need to
INSTALL file that comes with the distribution.

If you have a Microsoft Windows machine with ActiveState's Perl (
http://www.activestate.com), there's a PPM file available for Bioperl; at the time of
this writing, it's at http://bioperl.org/ftp/DIST/Bioperl-1.2.1.ppd.

There is also a CVS repository for Bioperl from which you can fetch the most current
versions of the modules. But be careful: some newer versions of the modules are
Bioperl web page.
All these methods for installing Bioperl are fine, but probably the most common way for Perl
but it's worth discussing again as it relates to Bioperl.
To install Bioperl, you start by typing the following at the command line:
perl -MCPAN -e shell;
This gives the CPAN shell prompt:
cpan>
It's often the case that a module you want to install may require other modules for its proper
can configure it to automatically follow and install missing prerequisites.
prerequisites crop up. When I asked my CPAN session how it was configured:
cpan> o conf
one of the lines of output from that query was:
prerequisites_policy ask
I couldn't find a way to list the options within my CPAN session, so I took a look at the CPAN
documentation in another window with perldoc CPAN, searched for the string
prerequisites_policy, and read the following:
prerequisites_policy
                  what to do if you are missing module prerequisites
                  ('follow' automatically, 'ask' me, or 'ignore')
